#!/usr/bin/env python3
"""生成 tokenizer 差分测试夹具。

用 HuggingFace tokenizers 库（权威参考实现）对语料编码，输出两份产物：
  - tests/data/tokenizer_fixture.json : 人类可读的对照基准（text -> ids）
  - tests/tokenizer_fixture_cases.h   : 供 C++ 测试直接 #include 的用例表

用法: python3 scripts/gen_tokenizer_fixture.py <tokenizer.json 路径> [输出目录]
"""
import json
import sys
from pathlib import Path

from tokenizers import Tokenizer

CORPUS = [
    "Hello, world!",
    "The quick brown fox jumps over the lazy dog.",
    "I'm sure they'll we've don't can't won't it's he's she's",
    "I’m sure they’ll don’t it’s",  # U+2019 撇号
    "你好，世界！今天天气不错。",
    "使用CUDA kernel实现FlashAttention，速度提升2倍。",
    "pi=3.14159, e=2.71828; 12345 67890 0x1F4A9",
    "!@#$%^&*()_+-=[]{}|;:'\",.<>/?~`",
    "a   b\nc\t\t d\r\ne",
    "  hello  ",
    "\n\nfoo\nbar\r\n\r\nbaz",
    "int main(int argc, char **argv) { return 0; }",
    "def fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)",
    "Artificial intelligence infrastructure includes GPU clusters, "
    "high-bandwidth memory, NVLink, and RDMA networking. FlashAttention "
    "reduces HBM accesses from O(N^2) to O(N) by tiling and online softmax.",
    "大语言模型推理系统通常包含预填充（prefill）与解码（decode）两个阶段，"
    "KV Cache 的分页管理（PagedAttention）和连续批处理（continuous batching）"
    "是提升吞吐的关键技术。",
    "😀🎉🚀💯🔥",
    "café naïve Zürich straße",
    "Ω≈ç√∫˜µ≤≥÷",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    " ",
    "      ",
    "\t\t\t",
    "Qwen2.5-0.5B-Instruct 的词表大小是 151936。",
    "mixed 中英 mixed 123 mixed 标点，。！？",
    "trailing space here ",
    " leading space here",
    "<|im_start|>user\n你好<|im_end|>",
    "url: https://github.com/aicl-lab/tiny-llm/pull/42#issuecomment",
    "path: /home/user/file.tar.gz; C:\\Users\\test",
    "math: x² + y² = z², ∑ᵢ aᵢ = 42",
]


def cpp_string(s: str) -> str:
    """转义为安全的 C++ 窄字符串字面量（源文件 UTF-8）。"""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 0x20 or o == 0x7F:
            out.append("\\%03o" % o)  # 3 位八进制，C++ 中至多取 3 位，无歧义
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    tok = Tokenizer.from_file(sys.argv[1])
    tok.no_truncation()
    cases = []
    for text in CORPUS:
        ids = tok.encode(text, add_special_tokens=False).ids
        cases.append({"text": text, "ids": ids})

    out_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("tests")
    json_path = out_dir / "data" / "tokenizer_fixture.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"tokenizer": sys.argv[1], "cases": cases}, f, ensure_ascii=False, indent=1)

    header_path = out_dir / "tokenizer_fixture_cases.h"
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("// GENERATED by scripts/gen_tokenizer_fixture.py -- do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n#include <vector>\n\n")
        f.write("namespace tiny_llm::test_fixture {\n\n")
        f.write("struct Case {\n    const char *text;\n    std::vector<int> ids;\n};\n\n")
        f.write("inline const Case kCases[] = {\n")
        for c in cases:
            ids = ", ".join(str(i) for i in c["ids"])
            f.write(f"    {{ {cpp_string(c['text'])}, {{{ids}}} }},\n")
        f.write("};\n\n")
        f.write("inline constexpr std::size_t kCaseCount = std::size(kCases);\n\n")
        f.write("} // namespace tiny_llm::test_fixture\n")
    total = sum(len(c["ids"]) for c in cases)
    print(f"wrote {json_path} and {header_path}: {len(cases)} cases, {total} tokens")


if __name__ == "__main__":
    main()
